baseurl = "https://example.org/"
languageCode = "de_DE"
title = "Kindergarten St. Michael"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Ingo Kempf"
	description = "A material design theme for documentations."
	copyright = "Released under the MIT license"

	# Repository
	#provider = "GitHub"
	#repo_url = "https://github.com/digitalcraftsman/hugo-material-docs"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "cyan"
    	accent  = "light-blue" 

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"
        #text = "Roboto"
        #code = "Roboto Mono"

[social]
	twitter = ""
	github  = "digitalcraftsman"
	email   = "hello@email.com"


[[menu.main]]
	name   = "Startseite"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Unser Kindergarten"
	url    = "about/"
	weight = 10

[[menu.main]]
	name   = "Unsere Ziele"
	url    = "goals/"
	weight = 20

[[menu.main]]
	name   = "Kleinkindgruppe"
	url    = "toddler/"
	weight = 30

[[menu.main]]
	name   = "Vorschule"
	url    = "preschool/"
	weight = 40

[[menu.main]]
	name   = "Elternbeirat"
	url    = "parentscouncil/"
	weight = 50    

[[menu.main]]
	name   = "Aktuelle Termine"
	url    = "calendar/"
	weight = 60


[[menu.main]]
	name   = "Informationen"
	url    = "information/"
	weight = 70

[[menu.main]]
	name   = "Bildergallerie"
	url    = "gallery/"
	weight = 80

[[menu.main]]
	name   = "Kontakt"
	url    = "contact/"
	weight = 90    

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
